
jobs:
- job: Windows_CI_Dev

  pool: Win-CPU

  steps:
    - task: CmdLine@1
      displayName: 'Get ONNX testdata'
      inputs:
        filename: azcopy
        arguments: ' /S /Source:https://onnxruntimetestdata.blob.core.windows.net/onnx-model-zoo-20181018 /Dest:$(Build.SourcesDirectory)\build\Windows\Debug\models /SourceKey:%AZURE_BLOB_KEY%'
      env:
        AZURE_BLOB_KEY: $(onnxruntime-storage-key)

    - task: BatchScript@1
      inputs:
        filename: build.bat
        arguments: ' --use_mkldnn --use_openmp --build_shared_lib --build_csharp --enable_onnx_tests'
        workingFolder: "$(Build.SourcesDirectory)"


